language: node_js
node_js:
  - "node"
  - "lts/*"
branches:
  only:
  - master
  - greenkeeper
  - /^greenkeeper/.*$/
install:
  - npm i -g npm@latest
  - npm ci
script:
  - npm test
after_script:
  - cat ./test/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
